#!/usr/bin/env bun
/**
 * Checks that the specified Docker project's containers are running
 * and writes the dynamic port mappings to .env.local
 */

import { join } from 'path'

const projectName = process.env.RAILWAY_PROJECT_NAME || 'youtube-rss'

async function getRunningContainers(): Promise<string[]> {
	const proc = Bun.spawn(['docker', 'ps', '--format', '{{.Names}}'])
	const text = await new Response(proc.stdout).text()
	const exitCode = await proc.exited
	if (exitCode !== 0) {
		console.error('\x1b[31m✗ Docker is not available (is it installed and running?)\x1b[0m')
		process.exit(1)
	}
	return text.trim().split('\n').filter(Boolean)
}

async function getContainerPort(containerName: string, containerPort: number): Promise<number> {
	const proc = Bun.spawn(['docker', 'port', containerName, containerPort.toString()])
	const text = await new Response(proc.stdout).text()
	const exitCode = await proc.exited
	if (exitCode !== 0) {
		throw new Error(`Failed to get port for ${containerName}:${containerPort}`)
	}
	// Output format: "0.0.0.0:12345" or "[::]:12345"
	const match = text.trim().match(/:(\d+)$/)
	if (!match) {
		throw new Error(`Could not parse port from: ${text}`)
	}
	return parseInt(match[1], 10)
}

async function writeEnvLocal(dbPort: number): Promise<void> {
	const envPath = join(import.meta.dir, '..', '.env.local')
	const content = `# Auto-generated by check-docker.ts - do not edit
DB_URL=postgres://root:password@localhost:${dbPort}/local
`
	await Bun.write(envPath, content)
}

async function main() {
	const running = await getRunningContainers()
	const projectContainers = running.filter((name) => name.startsWith(`${projectName}-`))

	if (projectContainers.length === 0) {
		console.error(`\x1b[31m✗ No Docker containers running for ${projectName}\x1b[0m`)
		console.error(`\nRun: \x1b[33mbun run docker:start\x1b[0m`)
		process.exit(1)
	}

	const dbContainer = projectContainers.find((name) => name.includes('-db-'))

	if (!dbContainer) {
		console.error('\x1b[31m✗ Could not find db container\x1b[0m')
		console.error('Found containers:', projectContainers)
		process.exit(1)
	}

	const dbPort = await getContainerPort(dbContainer, 5432)

	await writeEnvLocal(dbPort)

	console.log(`\x1b[32m✓ Docker verified (${projectContainers.length} containers)\x1b[0m`)
	console.log(`  db: localhost:${dbPort}`)
}

main().catch((err) => {
	console.error('\x1b[31m✗ Unexpected error:\x1b[0m', err.message)
	process.exit(1)
})
