#!/usr/bin/env bun
/**
 * Resolves the Compose database service's published port
 * and writes the dynamic port mappings to .env.local
 */

import { join } from 'path'

import { getServicePort } from './compose'

async function writeEnvLocal(dbPort: number): Promise<void> {
	const envPath = join(import.meta.dir, '..', '.env.local')
	const content = `# Auto-generated by check-docker.ts - do not edit
DB_URL=postgres://root:password@localhost:${dbPort}/local
`
	await Bun.write(envPath, content)
}

async function main() {
	const dbPort = await getServicePort('db', 5432)

	await writeEnvLocal(dbPort)

	console.log(`\x1b[32m✓ Docker database port resolved\x1b[0m`)
	console.log(`  db: localhost:${dbPort}`)
}

main().catch((err) => {
	console.error('\x1b[31m✗ Unexpected error:\x1b[0m', err.message)
	process.exit(1)
})
